[2024-08-10T11:15:18.443+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-10T11:15:18.465+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pollution_air_dags.extract_air_pollution manual__2024-08-10T08:15:05.696831+00:00 [queued]>
[2024-08-10T11:15:18.476+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pollution_air_dags.extract_air_pollution manual__2024-08-10T08:15:05.696831+00:00 [queued]>
[2024-08-10T11:15:18.477+0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-10T11:15:18.521+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_air_pollution> on 2024-08-10 08:15:05.696831+00:00
[2024-08-10T11:15:18.539+0300] {standard_task_runner.py:64} INFO - Started process 960 to run task
[2024-08-10T11:15:18.551+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pollution_air_dags', 'extract_air_pollution', 'manual__2024-08-10T08:15:05.696831+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/air_pollution_dags.py', '--cfg-path', '/tmp/tmp82j6izhv']
[2024-08-10T11:15:18.554+0300] {standard_task_runner.py:91} INFO - Job 94: Subtask extract_air_pollution
[2024-08-10T11:15:18.626+0300] {task_command.py:426} INFO - Running <TaskInstance: pollution_air_dags.extract_air_pollution manual__2024-08-10T08:15:05.696831+00:00 [running]> on host DESKTOP-DKUGVOH.
[2024-08-10T11:15:18.742+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pollution_air_dags' AIRFLOW_CTX_TASK_ID='extract_air_pollution' AIRFLOW_CTX_EXECUTION_DATE='2024-08-10T08:15:05.696831+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-10T08:15:05.696831+00:00'
[2024-08-10T11:15:18.744+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-10T11:15:18.745+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-10T11:15:18.746+0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/florentino/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/florentino/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/florentino/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/florentino/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/florentino/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/florentino/airflow/dags/extract_air_pollution.py", line 5, in extract_air_pollution
    with open('air_pollution_data.csv', mode='r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'air_pollution_data.csv'
[2024-08-10T11:15:18.753+0300] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=pollution_air_dags, task_id=extract_air_pollution, run_id=manual__2024-08-10T08:15:05.696831+00:00, execution_date=20240810T081505, start_date=20240810T081518, end_date=20240810T081518
[2024-08-10T11:15:18.778+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 94 for task extract_air_pollution ([Errno 2] No such file or directory: 'air_pollution_data.csv'; 960)
[2024-08-10T11:15:18.805+0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-10T11:15:18.830+0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-10T11:15:18.831+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
