[2024-08-10T11:36:38.539+0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-10T11:36:38.568+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pollution_air_dags.transform_data manual__2024-08-10T08:31:21.151531+00:00 [queued]>
[2024-08-10T11:36:38.580+0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pollution_air_dags.transform_data manual__2024-08-10T08:31:21.151531+00:00 [queued]>
[2024-08-10T11:36:38.580+0300] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-10T11:36:38.606+0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-08-10 08:31:21.151531+00:00
[2024-08-10T11:36:38.619+0300] {standard_task_runner.py:64} INFO - Started process 6855 to run task
[2024-08-10T11:36:38.633+0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'pollution_air_dags', 'transform_data', 'manual__2024-08-10T08:31:21.151531+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/air_pollution_dags.py', '--cfg-path', '/tmp/tmptw1lz4jw']
[2024-08-10T11:36:38.638+0300] {standard_task_runner.py:91} INFO - Job 100: Subtask transform_data
[2024-08-10T11:36:38.717+0300] {task_command.py:426} INFO - Running <TaskInstance: pollution_air_dags.transform_data manual__2024-08-10T08:31:21.151531+00:00 [running]> on host DESKTOP-DKUGVOH.
[2024-08-10T11:36:38.829+0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='pollution_air_dags' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-10T08:31:21.151531+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-10T08:31:21.151531+00:00'
[2024-08-10T11:36:38.832+0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-10T11:36:38.833+0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-10T11:36:38.834+0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/florentino/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/florentino/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/florentino/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/florentino/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/florentino/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: transform_data() missing 1 required positional argument: 'data'
[2024-08-10T11:36:38.842+0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pollution_air_dags, task_id=transform_data, run_id=manual__2024-08-10T08:31:21.151531+00:00, execution_date=20240810T083121, start_date=20240810T083638, end_date=20240810T083638
[2024-08-10T11:36:38.920+0300] {standard_task_runner.py:110} ERROR - Failed to execute job 100 for task transform_data (transform_data() missing 1 required positional argument: 'data'; 6855)
[2024-08-10T11:36:38.928+0300] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-10T11:36:38.980+0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-10T11:36:38.996+0300] {local_task_job_runner.py:222} INFO - ::endgroup::
